### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by VahidNaderi** [VahidNaderi/googlerankchecker#12]
- [ ] Refactor current code
- [x] Migrate to type script
- [ ] Debug placement inconsistency issue
- [ ] Add rank history
- [ ] Create an intro video
- [ ] Improve website favicon detection
